name: PR Checker

#  To stop the old workflow if the new commit comes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  statuses: write 
  
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.paths.outputs.frontend }}
      backend_changed: ${{ steps.paths.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for changes in paths
        id: paths
        uses: dorny/paths-filter@v3.0.1
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'  

  frontend-build:
    needs: filter-changes
    name: Frontend Build Test
    runs-on: ubuntu-latest
    if: needs.filter-changes.outputs.frontend_changed == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.MY_PAT }}  # To re-triggere the workflow
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install and Build Frontend
        if: needs.filter-changes.outputs.frontend_changed == 'true'
        working-directory: frontend
        run: |
          npm ci
          npm run format:check
          npm run lint
          npm run build
          

  backend-build:
    needs: filter-changes
    name: Backend Build Test
    runs-on: ubuntu-latest
    if: needs.filter-changes.outputs.backend_changed == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.MY_PAT }}  # To re-triggere the workflow
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install and Build Backend
        if: needs.filter-changes.outputs.backend_changed == 'true'
        working-directory: backend
        run: |
          npm ci
          npm run format:check
          npm run lint
          npm run build